#ifndef LIBPROJ_TEST_GLOBAL_H
#define LIBPROJ_TEST_GLOBAL_H

#include <QtGlobal>

#if defined(LIBPROJ_TEST_LIBRARY)
#  define LIBPROJ_TESTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBPROJ_TESTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBPROJ_TEST_GLOBAL_H

