#ifndef LIBPROJTEST_GLOBAL_H
#define LIBPROJTEST_GLOBAL_H

#include <QtGlobal>

#if defined(LIBPROJTEST_LIBRARY)
#  define LIBPROJTESTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBPROJTESTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBPROJTEST_GLOBAL_H

