
INCLUDE(FindPackageHandleStandardArgs)
FIND_PROGRAM(GCOV_EXECUTABLE gcov HINTS ${GCOV_ROOT})
FIND_PACKAGE_HANDLE_STANDARD_ARGS(gcov DEFAULT_MSG GCOV_EXECUTABLE)
# only visible in advanced view
MARK_AS_ADVANCED(GCOV_EXECUTABLE)
