
INCLUDE(FindPackageHandleStandardArgs)
FIND_PROGRAM(DOXYGEN_EXECUTABLE doxygen HINTS ${DOXYGEN_ROOT})
FIND_PACKAGE_HANDLE_STANDARD_ARGS(doxygen DEFAULT_MSG DOXYGEN_EXECUTABLE)
# only visible in advanced view
MARK_AS_ADVANCED(DOXYGEN_EXECUTABLE)

if(NOT DOXYGEN_EXECUTABLE)
 set(DOXYGEN_FOUND FALSE)
 message("Doxygen not found! You can't generate documentation...")
elseif(NOT DOXYGEN_EXECUTABLE)
 set(DOXYGEN_FOUND TRUE)
endif()